version: '3'

services:
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: EventosDit
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    links:
      - db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: eventos@dit.edu
      PGADMIN_DEFAULT_PASSWORD: EventosDit
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
  pgadmin: