# Generated by Django 2.2 on 2019-06-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20190504_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default='', upload_to='imagenes'),
            preserve_default=False,
        ),
    ]
