# Generated by Django 2.2 on 2019-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
