# Generated by Django 2.2 on 2019-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, db_table='curso_alumnos', related_name='cursos', to='participantes.Alumno'),
        ),
    ]
