# Generated by Django 2.2 on 2019-09-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20190903_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='presentes',
            field=models.ManyToManyField(blank=True, db_table='asistencias', related_name='asistencias', to='participantes.Alumno'),
        ),
    ]
