# Generated by Django 2.2 on 2019-04-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('documento', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Rol'), (1, 'alumno'), (2, 'profesor'), (3, 'disertante'), (4, 'organizador')])),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='participantes.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participantes.Rol')),
            ],
            options={
                'db_table': 'alumnos',
            },
            bases=('participantes.rol',),
        ),
        migrations.CreateModel(
            name='Disertante',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participantes.Rol')),
            ],
            options={
                'db_table': 'disertantes',
            },
            bases=('participantes.rol',),
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participantes.Rol')),
            ],
            options={
                'db_table': 'organizadores',
            },
            bases=('participantes.rol',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='participantes.Rol')),
            ],
            options={
                'db_table': 'profesores',
            },
            bases=('participantes.rol',),
        ),
    ]
