# Generated by Django 2.2 on 2019-05-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='personas',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
    ]
